#!/bin/bash

#this script file concatenate the commits in a file
#takes file name as an argument

if [ ! $# -eq 1 ]
then
	echo "Enter name of svn file to buffer commits"
fi

source_file=$1
dest_file=$( echo $source_file.buf )
