#!/bin/bash

if [ -f 1* ]
then
	rm 1*
fi

if [ -f 2* ]
then
	rm 2*
fi

if [ -f 3* ]
then
	rm 3*
fi

if [ -f 4* ]
then
	rm 4*
fi

if [ -f 5* ]
then
	rm 5*
fi

if [ -f 6* ]
then
	rm 6*
fi

if [ -f 7* ]
then
	rm 7*
fi

if [ -f 8* ]
then
	rm 8*
fi

if [ -f 9* ]
then
	rm 9*
fi

if [ -f svnscript* ]
then
	rm svnscript*
fi

if [ -f SvnGit* ]
then
	rm SvnGit*
fi
