#!/bin/bash

if [ $# -eq 0 ]
then
	echo "Enter file name, svn url and instanceID"
	exit
fi

cp /bin/svnscript ./
mv svnscript "svnscript$2"
cp src/SvnGit4.java ./
javac SvnGit4.java
java SvnGit4 $1 $2



#svn diff -c $1  file:///home/effortmetrics/repodump/mirr > $1

